name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Certifique-se de que suas dependências estejam listadas aqui

      - name: Run tests
        run: |
          python -m unittest discover -s tests

      - name: Increment version
        run: |
          version=$(cat version.txt)
          new_version=$(echo $version | awk -F. -v OFS=. '{$NF++; print}')
          echo $new_version > version.txt
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add version.txt
          git commit -m "Atualiza para versão $new_version"
          git push
        if: success()
